name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 */5 * *'
  workflow_dispatch:

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive request
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/${{ secrets.SUPABASE_TABLE_NAME }}?select=*&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"

#původní script jen pingne databázi
#name: Keep Supabase Alive
#
#on:
#  schedule:
    # Spustí se každé 5 dny ve 00:00 (Supabase vypíná po 7 dnech)
#    - cron: '0 0 */5 * *'
#  workflow_dispatch: # Umožňuje spustit test ručně tlačítkem

#jobs:
#  ping_supabase:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send keep-alive request
#        run: |
#          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/" \
#          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
#          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
